# Generated by Django 6.0.4 on 2026-04-28 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Аты')),
                ('phone', models.CharField(max_length=30, verbose_name='Телефон')),
                ('question', models.TextField(verbose_name='Сұрақ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
